{"version":1,"ops":[{"type":1,"author":{"id":"7fc094c5f01526c965e541ec82007c487f6fa288"},"timestamp":1597783040,"metadata":{"github-id":"MDU6SXNzdWU2ODEzMjYwOTM=","github-url":"https://github.com/hexatomic/hexatomic/issues/214","origin":"github"},"title":"Trying to save document edited and saved across 2 editors throws InvocationTargetException","message":"**Describe the bug**\n\nWhen editing and saving one and the same document across two editors, you may run into an `InvocationTargetException` when saving.\n\n**To reproduce the bug**\nSteps to reproduce the behavior:\n1. Open example corpus\n2. Open doc1 with graph editor (editor1)\n3. Do `t test`\n4. Save\n5. Open doc1 in a second graph editor (editor2)\n6. Do `t test2`\n7. Save\n8. (Re-)Activate editor1\n9. Do `t test3`\n10. Save\n11. See error\n\n**Expected behavior**\n\nI would expect that in neither combination of editing and saving of one document from more than one editor would throw an exception on saving.\n\n**Screenshots**\n\n![Peek 2020-08-18 22-29](https://user-images.githubusercontent.com/3007126/90562622-cd16da80-e1a2-11ea-8c34-0c0771937a4d.gif)\n\n\n**Desktop (please complete the following information):**\n - Operating System: Ubuntu 20.04\n - Hexatomic Version: 0.4.2\n - Java Version: AdoptOpenJDK 11\n \n\n**Additional context**\n\n- Doesn't seem to be a timing issue. Waiting for a few secs between each action doesn't change the outcome.\n- Doesn't seem to be an issue with the Grid Editor... Doing the same and changing annotation values doesn't produce the error.\n- Perhaps this has to do with tokenization?","files":null}]}